# Generated by Django 5.0.6 on 2024-06-01 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_profile',
        ),
    ]
